### ISSUE TITLE
install error in centos

### ISSUE THREAD

**Issue by asmlgkj** [gfkse/bettermc#1]
Thanks a lot, can you have a look at this error
![image](https://user-images.githubusercontent.com/50854682/203543610-9a9010d6-9f02-49c3-a2fa-ea4008d1073c.png)

**Comment by asmlgkj** [comment]
in windows
![image](https://user-images.githubusercontent.com/50854682/203545078-caa33c66-dd0a-4c85-8b8d-e34a4ef36543.png)

**Comment by akersting** [comment]
The error you are getting on Windows is in no way related to the installation of this specific package. Apparently, you do not have RTools (https://cran.r-project.org/bin/windows/Rtools/) installed. Any particular reason why you do not simply install the binary package from CRAN?

Regarding CentOS: I assume you are using a fairly old version of it!? I just tested with the latest version (using https://hub.docker.com/_/centos) and there is no error. Probably, your old version of `gcc` does not understand `_Generic`.

**Comment by asmlgkj** [comment]
Thanks  a lot.
